### ISSUE TITLE
What does input source do when all files are defined in the config?

### ISSUE THREAD

**Issue by mbcooper** [lazd/gulp-karma#35]
More of a question...

If I define all my .spec.js and .js files in the karma config file... what files should I be piping in and what effect they they have?

i tried it with a null set, but that throws.  And no matter what I set as source, it runs all the tests.

Sort of confusing syntax..

Any explanation?

thanks

--mike

**Comment by adamfitz77hob** [comment]
It's been several months since this question was asked, but it caught my eye.  At the risk of stepping on Mr. Davis' toes, I'll venture an answer.

When I use gulp-karma, I leave the file definitions in the config file empty, and rely entirely on files passed in.  I use this only when I need a higher degree of flexibility with regard to the location of dependency, application and spec files.

If I know that my required files will always be available in certain locations (usually the case), I populate the `files` array in karma config, and I directly access the karma public api ([karma-runner/gulp-karma](https://github.com/karma-runner/gulp-karma)) instead of lazd's plugin.  In my experience, defining your files in the config file obviates the need for this particular plugin.

**Comment by lazd** [comment]
`gulp-karma` is deprecated (#43). Please use Karma directly: https://github.com/karma-runner/gulp-karma
