### ISSUE TITLE
WARN `start` method is deprecated since 0.13

### ISSUE THREAD

**Issue by bristoljon** [lazd/gulp-karma#50]
Maybe this is not gulp-karma problem but always get this warning when starting tests with gulp. Seems gulp-karma is using old start method for karma? 

Here's my gulpfile.js:

var karma = require('gulp-karma');

...

var testFiles = [
    './src/js/*.js',
    './spec/js/*.spec.js'
];

gulp.task('test', function() {
  console.log("It's testing...".random)
  return gulp.src(testFiles)
    .pipe(karma({
      configFile: 'karma.conf.js',
      action: 'run'
    }))
    .on('error', function(err) {
      // Make sure failed tests cause gulp to exit non-zero
      throw err;
    });
});

And full warning:

[11:01:35] Starting Karma server...
WARN `start` method is deprecated since 0.13. It will be removed in 0.14. Please use 
  server = new Server(config, [done])
  server.start()
instead.

New to gulp, npm, karma and testing in general so could well be me!

**Comment by lazd** [comment]
`gulp-karma` is deprecated (#43). Please use Karma directly: https://github.com/karma-runner/gulp-karma

**Comment by adamreisnz** [comment]
That's a bummer. How can I dynamically add files to karma without maintaining a list of files in the karma config file? With gulp-karma this worked great, because I could just feed the source files to the plugin. How do I tackle this without the gulp-karma plugin? If that's not possible, it seems like a reasonable use case for keeping gulp-karma.

**Comment by adamreisnz** [comment]
Never mind that, apparently I can just specify the files list in runtime as well. Cheers.
